<link rel="stylesheet" href="assets/css/login.css">


<?php
$controller = new MainController('http://backend:5763/');
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST)) {  
  $login = $_POST['login'];
  $password = $_POST['password'];

  $result = $controller->connect_user($login, $password);
}
?>

<h2>Log to your Account</h2>
<form method="POST" action="?page=login">
  <div class="container">
    <label for="login"><b>Username</b></label>
    <input type="login" placeholder="Enter Username" name="login" required>

    <label for="password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>

    <button type="submit">Login</button>
  </div>
</form>

<h2>Create a New User</h2>
    <form method="POST" action="?page=user">
        <label for="firstname">Firstname:</label>
        <input type="text" id="firstname" name="firstname" required><br>
        
        <label for="lastname">Lastname:</label>
        <input type="text" id="lastname" name="lastname" required><br>
        
        <label for="email">Email:</label>
        <input type="email" id="email" name="email" required><br>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required><br>

        <label for="password_repeat">Password repeat:</label>
        <input type="password" id="password_repeat" name="password_repeat" required><br>
        
        <button type="submit">Create User</button>
    </form>